include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

linter:
  rules:
    # Estilo de código
    - always_declare_return_types
    - avoid_empty_else
    - avoid_print
    - avoid_renaming_method_parameters
    - avoid_returning_null
    - avoid_unused_constructor_parameters
    - curly_braces_in_flow_control_structures
    - empty_catches
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    
    # Calidad de código
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_dynamic_calls
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_type_to_string
    - cancel_subscriptions
    - comment_references
    - control_flow_in_finally
    - directives_ordering
    - empty_statements
    - invariant_booleans
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - only_throw_errors
    - prefer_conditional_assignment
    - prefer_const_constructors_in_immutables
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_foreach
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps